### ISSUE TITLE
rnv run -p androidtv without simulator results in launching simulator but not recognising it

### ISSUE THREAD

**Issue by pavjacko** [renative-org/renative#104]
ReNative run - _runGradle:androidtv - Starting!

ReNative run - _listAndroidTargets:androidtv - Starting!
execCLI:null:echo "avd name" | nc localhost 5554
execCLI:null:echo "avd name" | nc localhost 5556
Can't find service: tv_input
Can't find service: tv_input
? What emulator would you like to start? Android_TV_1080p_API_22 | TV 📺  | arch: x86 | udid: unknown

ReNative run - launchAndroidSimulator:androidtv:Android_TV_1080p_API_22 - Starting!
execCLI:androidEmulator:-avd "Android_TV_1080p_API_22"

ReNative run - _listAndroidTargets:androidtv - Starting!
execCLI:null:echo "avd name" | nc localhost 5554
execCLI:null:echo "avd name" | nc localhost 5556
Can't find service: tv_input
Can't find service: tv_input
looking for active emulators: attempt 1/10

ReNative run - _listAndroidTargets:androidtv - Starting!
execCLI:null:echo "avd name" | nc localhost 5554
execCLI:null:echo "avd name" | nc localhost 5556
Can't find service: tv_input
Can't find service: tv_input
looking for active emulators: attempt 2/10

ReNative run - _listAndroidTargets:androidtv - Starting!
execCLI:null:echo "avd name" | nc localhost 5554
execCLI:null:echo "avd name" | nc localhost 5556
Can't find service: tv_input
Can't find service: tv_input
looking for active emulators: attempt 3/10

ReNative run - _listAndroidTargets:androidtv - Starting!
execCLI:null:echo "avd name" | nc localhost 5554
execCLI:null:echo "avd name" | nc localhost 5556
Can't find service: tv_input
Can't find service: tv_input
looking for active emulators: attempt 4/10

ReNative run - _listAndroidTargets:androidtv - Starting!
execCLI:null:echo "avd name" | nc localhost 5554
execCLI:null:echo "avd name" | nc localhost 5556
Can't find service: tv_input
Can't find service: tv_input
looking for active emulators: attempt 5/10

ReNative run - _listAndroidTargets:androidtv - Starting!
execCLI:null:echo "avd name" | nc localhost 5554
execCLI:null:echo "avd name" | nc localhost 5556
Can't find service: tv_input
Can't find service: tv_input
looking for active emulators: attempt 6/10

ReNative run - _listAndroidTargets:androidtv - Starting!
execCLI:null:echo "avd name" | nc localhost 5554
execCLI:null:echo "avd name" | nc localhost 5556
Can't find service: tv_input
Can't find service: tv_input
looking for active emulators: attempt 7/10

ReNative run - _listAndroidTargets:androidtv - Starting!
execCLI:null:echo "avd name" | nc localhost 5554
execCLI:null:echo "avd name" | nc localhost 5556
Can't find service: tv_input
Can't find service: tv_input
looking for active emulators: attempt 8/10

ReNative run - _listAndroidTargets:androidtv - Starting!
execCLI:null:echo "avd name" | nc localhost 5554
execCLI:null:echo "avd name" | nc localhost 5556
Can't find service: tv_input
Can't find service: tv_input
looking for active emulators: attempt 9/10

ReNative run - _listAndroidTargets:androidtv - Starting!
execCLI:null:echo "avd name" | nc localhost 5554
execCLI:null:echo "avd name" | nc localhost 5556
Can't find service: tv_input
Can't find service: tv_input
looking for active emulators: attempt 10/10

ReNative run - _askForNewEmulator - Starting!

 ❓ Do you want ReNative to create new Emulator (Android_TV_1080p_API_22) for you? (y) to confirm:

**Comment by gmoz22** [comment]
Same issue here
```
? What emulator would you like to start? Android_TV_720p_API_24 | TV 📺  | arch: x86 | udid: unknown
$ rnv run -p androidtv - launchAndroidSimulator:androidtv:Android_TV_720p_API_24 - Starting!
execCLI:androidEmulator:-avd "Android_TV_720p_API_24"
$ rnv run -p androidtv - _checkForActiveEmulator:androidtv - Starting!
$ rnv run -p androidtv - _listAndroidTargets:androidtv:false:true:false - Starting!
looking for active emulators: attempt 1/10
$ rnv run -p androidtv - _listAndroidTargets:androidtv:false:true:false - Starting!
looking for active emulators: attempt 2/10
$ rnv run -p androidtv - _listAndroidTargets:androidtv:false:true:false - Starting!
looking for active emulators: attempt 3/10
$ rnv run -p androidtv - _listAndroidTargets:androidtv:false:true:false - Starting!
looking for active emulators: attempt 4/10
$ rnv run -p androidtv - _listAndroidTargets:androidtv:false:true:false - Starting!
looking for active emulators: attempt 5/10
$ rnv run -p androidtv - _listAndroidTargets:androidtv:false:true:false - Starting!
looking for active emulators: attempt 6/10
$ rnv run -p androidtv - _listAndroidTargets:androidtv:false:true:false - Starting!
looking for active emulators: attempt 7/10
$ rnv run -p androidtv - _listAndroidTargets:androidtv:false:true:false - Starting!
looking for active emulators: attempt 8/10
$ rnv run -p androidtv - _listAndroidTargets:androidtv:false:true:false - Starting!
looking for active emulators: attempt 9/10
$ rnv run -p androidtv - _listAndroidTargets:androidtv:false:true:false - Starting!
looking for active emulators: attempt 10/10
┌──────────────────────────────────────────────────────────────────────────────┐
│  🚀  SUMMARY | 8/8/2019, 1:46:13 PM                                          │
│  $ rnv run -p androidtv                                                      │
├──────────────────────────────────────────────────────────────────────────────┤
│  Project Name: hello-renative                                                │
│  Project Version: 0.1.0                                                      │
│  App Config: helloWorld                                                      │
│  Supported Platfroms: androidtv                                              │
│  Master Template: renative-template-hello-world                              │
│  Env Info: darwin | x64 | node v10.13.0 | rnv v0.24.0-alpha10                │
│  Platform: androidtv                                                         │
│  Executed Time: 0h:0m:52s:96ms                                               │
│                                                                              │
│ ⚠️  $ rnv run -p androidtv - WARNING: You're missing /Users/steve/.rnv/hello-renative/appConfigs/helloWorld/config.private.json for this app: . You won't be able to make production releases without it!
│ 🛑  $ rnv run -p androidtv - ERRROR! Could not find any active emulatros
│                                                                              │
└──────────────────────────────────────────────────────────────────────────────┘
```

**Comment by chwagssd** [comment]
I have this same issue. I was able to resolve it by changing a setting on my virtual device:

![image](https://user-images.githubusercontent.com/294938/62738188-88c8fa00-b9e6-11e9-9c46-1d08e9564c24.png)

1. Under "Advanced Settings" > "Boot Option", select the "Cold boot" option
2. Open 2 terminal windows
   - `rnv start`
   - `rnv run -p androidtv`

It will boot up the AndroidTV emulator, take some amount of time, and then wala!!!

![image](https://user-images.githubusercontent.com/294938/62738272-c0d03d00-b9e6-11e9-8818-373361da32db.png)

I think this process doesn't work when reloading a saved image because it adds something to the boot loader/startup sequence to connect for a live streaming install onto the device.

**Comment by mihaiblaga89** [comment]
Unstale

**Comment by mihaiblaga89** [comment]
This is happening again, reopening

**Comment by mihaiblaga89** [comment]
should be fixed by now
