### ISSUE TITLE
navigation object do not pass props (react-navigation)

### ISSUE THREAD

**Issue by Ivanov89** [renative-org/renative#214]
RNV version: 0.25.7
React navigation: 3.9.2

When trying to pass props from `GameSectionComponent` to `ScreenGame` , the props are not existing in the navigation object, neither in the `navigation.state` :

After reading the docs, I tried following in the `GameSectionComponent`:
` Api.navigation.navigate("Game", { gameName: "test123" })`

or

`this.props.navigation.setParams({ gameName: 'test123' })`

And in the ScreenGame:

`const { gameName } = this.props.navigation.getParam('gameName');`

Not sure do I have change the default navigation structure here:

`const navStructure = {
    root: {
        menus: {
            drawerMenu: {
                position: 'left',
                isVisibleIn: [IOS, ANDROID],
                component: 'Menu',
                options: {
                    drawerBackgroundColor: Theme.color1,
                    drawerWidth: 250
                },
                navigationOptions: {},
            },
            sideMenu: {
                position: 'left',
                isVisibleIn: [MACOS, WINDOWS],
                component: 'Menu',
                options: {
                    menuWidth: 250
                },
                navigationOptions: {},
            },
            topMenu: {
                isVisibleIn: [TVOS, ANDROID_TV, TIZEN, FIREFOX_TV, WEB, WEBOS],
                component: 'Menu',
                options: {
                    menuHeight: 100
                },
                navigationOptions: {},
            },
            tabMenu: {
                position: 'bottom',
                isVisibleIn: [TVOS, ANDROID_TV, TIZEN],
                component: 'Menu',
                navigationOptions: {},
            },
            modalMenu: {
                position: 'hidden',
                isVisibleIn: [KAIOS],
                component: 'Menu',
                navigationOptions: {},
            },
            swipeMenu: {
                isVisibleIn: [ANDROID_WEAR, TIZEN_WATCH],
            },
        },
        screens: {

            Login: {
                screen: 'ScreenLogin',
                tabMenu: {
                    position: 'bottom',
                    isVisibleIn: [IOS, ANDROID],
                    screens: ['ScreenLogin'],
                },
                navigationOptions: {
                    title: 'Login'
                },
            },

            Register: {
                screen: 'ScreenRegister',
                tabMenu: {
                    position: 'bottom',
                    isVisibleIn: [IOS, ANDROID],
                    screens: ['ScreenRegister'],
                },
                navigationOptions: {
                    title: 'Register'
                },
            },

            Splash: {
                screen: 'ScreenSplash',
                tabMenu: {
                    position: 'bottom',
                    isVisibleIn: [IOS, ANDROID],
                    screens: ['ScreenSplash'],
                },
                navigationOptions: {
                    title: 'Splash'
                },
            },

            MainLobby: {
                screen: 'ScreenMainLobby',
                tabMenu: {
                    position: 'bottom',
                    isVisibleIn: [IOS, ANDROID],
                    screens: ['ScreenMainLobby'],
                },
                navigationOptions: {
                    title: 'Main Lobby',

                },
            },
            Game: {
                screen: 'ScreenGame',
                tabMenu: {
                    position: 'bottom',
                    isVisibleIn: [IOS, ANDROID],
                    screens: ['ScreenGame'],
                },
                navigationOptions: {
                    title: 'Game'
                },
            },

        },
        navigationOptions: {
            headerTitleStyle: {
                color: Theme.color3,
                fontFamily: Theme.primaryFontFamily,
            },
            headerStyle: {
                backgroundColor: Theme.color1,
                borderBottomWidth: isTopMenuBased ? 0 : 1,
            },
            // headerLeft: (n) => {
            //     if (!isDrawerMenuBased()) return null;
            //     return (
            //         <Icon
            //             iconFont="ionicons"
            //             iconName="md-menu"
            //             iconColor={Theme.color3}
            //             style={{ width: 40, height: 40, marginLeft: 10 }}
            //             onPress={() => {
            //                 Api.navigation.openDrawer();
            //             }}
            //         />
            //     );
            // },
        },
    },
    stacks: {
        navigationOptions: {
            headerStyle: {
                backgroundColor: Theme.color1,
            },
            headerTintColor: Theme.color3,
            headerTitleStyle: {
                color: Theme.color3,
                fontFamily: Theme.primaryFontFamily,
            },
        },

    },
    modals: {
        screens: {
            MyModal: {
                screen: 'ScreenModal',
                navigationOptions: {
                    title: 'My Modal',
                },
            },
        },
        navigationOptions: {
            header: null,
        },
    },
};

export { navStructure, isDrawerMenuBased, isTopMenuBased }; `

Or how to pass props correctly in that version?
Thanks!

**Comment by pavjacko** [comment]
@Ivanov89  hmm that's weird as passing of params should work with this PR (already part of 0.25.7) https://github.com/pavjacko/renative/pull/178/files

could you open your package.lock file and check what is your "renative" (not "rnv") version?

**Comment by Ivanov89** [comment]
@pavjacko `renative` version is `0.25.7`

**Comment by maximilize** [comment]
@pavjacko This is another issue, I guess it's similar to this one: https://github.com/react-navigation/react-navigation/issues/143

**Comment by maximilize** [comment]
I was able to solve my problem with this solution: https://github.com/react-navigation/react-navigation/issues/3764#issuecomment-484431609

**Comment by mihaiblaga89** [comment]
considering this closed
