### ISSUE TITLE
I cannot run rnv command

### ISSUE THREAD

**Issue by jesusbarrientos** [renative-org/renative#421]
**Describe the bug**
I had a problem when I try to run rnv command.

[](url)
![image](https://user-images.githubusercontent.com/41140638/73617970-b3e17e80-4602-11ea-9ba9-6eae876aa2bb.png)

**Comment by mihaiblaga89** [comment]
That sounds like node can't build gyp. I think you need to install Python.

Please follow the requirements for windows from https://github.com/nodejs/node-gyp. You do not need to install `node-gyp`, you only need the requirements. Then run `npm i` again

**Comment by jesusbarrientos** [comment]
I installed Python v2.7 and windows-build-tools with `npm install --global --production windows-build-tools` and I have the same problem. I also have installed Visual Studio Community 2019 with ASP.NET.

**Comment by pavjacko** [comment]
@jesusbarrientos latest releases of node tend to have issues with node-gyp. not sure what is your exact node version but it sounds like v12.x.x
try to downgrade it to v10.19.0, clean project and run it again

**Comment by ryancwalsh** [comment]
Thanks. https://stackoverflow.com/a/56285684/470749 mentioned something similar. This worked for me: 
```
node --version
v12.16.1
sudo apt-get update
sudo apt-get install -y python3-pip build-essential libssl-dev libffi-dev python3-dev python3-venv python-django
nvm --version
0.35.3
nvm install 10
npm install rnv -g
```

**Comment by benz0is** [comment]
I get the same problem , when I try to run rnv new I get an error... What can I do ?

**Comment by pauliusguzas** [comment]
This issue seems to have a fix provided and also is not related to rnv itself, therefore closing. Feel free to reopen on create a new ticket if similar issue reoccurs
