### ISSUE TITLE
Can't automatically create an android(wear) emulator on OSX

### ISSUE THREAD

**Issue by timokorkalainen** [renative-org/renative#622]
**Describe the bug**
During the emulator setup Android avdmanager is asking if custom hardware profile should be created, but rnv does not allow answering the question and thus hanging the whole process. A workaround is to create the emulator manually using the Android SDK tools.

**To Reproduce**
1) Clean install of Renative (0.31.3) on OSX (10.15.7)
2) Run rnv new
3) Run rnv run
4) I chose to run as androidwear and asked for a new emulator (Android_Wear_Round_API_28) to be created
5) The process "hangs" on avdmanager asking "⠹ Do you wish to create a custom hardware profile? [no]". Rnv does not allow me to answer the question, and thus avdmanager waits indefinitely for the answer.

**Expected behavior**
Either "no" should be answered automatically or rnv should provide a method to answer the question interactively.

**Desktop (please complete the following information):**

-   OS: OSX 10.15.7
-   Node Version 14.15.1
-   RNV Version 0.31.3

**Additional context**
I did everything according to Renative Getting Started docs and made clean installs of everything.

**Comment by pauliusguzas** [comment]
Thanks for reporting an issue. 0.37.0-canary.4 does not have this issue anymore therefore closing, feel free to reopen again
