### ISSUE TITLE
Upgrading to react native 0.63

### ISSUE THREAD

**Issue by ix42** [renative-org/renative#632]
Are there any plans to upgrade react native to 0.63.4?

**Comment by pavjacko** [comment]
@ix42 yes. rnv 0.33 will aim to support latest RN

**Comment by TheDuc** [comment]
You could always modify `renative.json` to use a different version of react native.
for example:
```
    "plugins": {
        "react-native": {
            "version": "0.63.4"
        }
    }
```

then you have to run `rnv platform eject` to eject the platform(s) you are using and make the necessary changes there (for example modify the podfile for iOS).

**Comment by ix42** [comment]
Thank you, yes, this is the way i went about it and everything went fine

**Comment by pavjacko** [comment]
0.33.0 comes with support for react-native 0.63.4
