### ISSUE TITLE
Renative module not found when using monorepo

### ISSUE THREAD

**Issue by alaingoga** [renative-org/renative#650]
**Describe the bug**
When using generated project as part of monorepo using yarn workspace, `renative` module can't be found.

**To Reproduce**
1. Create a new project:
```rnv new```
2. Build initial assets
```rnv build -p web```
3. Copy new project into existing monorepo
Ex:
```
Monorepo root 
- packages
  - newProject
     .....
     - package.json
  - otherComponents
     - package.json
```

2. See error
```
ERROR in ./src/app/index.js
Module not found: Error: Can't resolve 'renative' in '/Users/Shared/Relocated_Items/Security/Work/GIT/ott/uvn-ott-apps/packages/news/src/app'
 @ ./src/app/index.js 3:14-33
 @ ./index.web.js
 @ multi (webpack)-dev-server/client?http://0.0.0.0:8080 (webpack)/hot/dev-server.js ./index.web.js
```

**Expected behavior**
Renative is supposed to hoist appropriately on yarn workspace. I'm trying to use nohoist but that create other issues with other dependencies

**Screenshots or copy&paste**
If applicable, copy&paste the output of the command. **Run the command with `-i` to get more debugging informations**

Monorepo looks like this:

![image](https://user-images.githubusercontent.com/658031/106181092-2714c680-616b-11eb-9ac2-27ab4aaecc64.png)

**Desktop (please complete the following information):**

-   OS: [e.g. osx, windows 7, ubuntu 16.04]
MacOS: 10.15.7

-   Node Version [e.g. v10.16.3]
v12.15.0

-   RNV Version [e.g. 0.25.0]
0.31.3

**Additional context**
The plan is to try to use common assets on multiple apps also explained on https://github.com/pavjacko/renative/issues/644

**Comment by alaingoga** [comment]
Adding nohoist for renative and root folder on metro.config.js fixed the issue on my end:

**root package.json**
```
{
  "name": "root",
  "private": true,
  "workspaces": {
    "packages": [
      "packages/*"
    ],
    "nohoist": [
      "**/renative"
    ]
  }
}
```

**metro.config.js**
```
const defaultConfig = {
    watchFolders: [
        path.resolve(__dirname, '../../'),
    ],
};
```

**Comment by airtonix** [comment]
eh `nohoist` really shouldn't be the solution.... you just end up with a monorepo that takes hours to install

**Comment by kasinskas** [comment]
hey, this is pretty old issue, but in case you or someone else still has this issue, try adding `"isMonorepo": true,` to `renative.json` of the project, in this case `news`

**Comment by pauliusguzas** [comment]
@alaingoga closing this ticket as a solution has been provided, if it still doesn't help feel free to reopen again
