### ISSUE TITLE
GitHub Discussions

### ISSUE THREAD

**Issue by iepsen** [renative-org/renative#670]
As [Spectrum announced](https://spectrum.chat/spectrum/general/join-us-on-our-new-journey~e4ca0386-f15c-4ba8-8184-21cf5fa39cf5) it will be ready only in favor of GitHub Discussions.

Do you have plans to move to GitHub Discussions?

**Comment by pavjacko** [comment]
@iepsen bit late response but yes!

we plan to launch GH discussions together with [0.33](https://github.com/pavjacko/renative/milestone/18)

**Comment by pavjacko** [comment]
new discussions section is now live
https://github.com/renative-org/renative/discussions
