### ISSUE TITLE
wearOs, fast refresh not working.

### ISSUE THREAD

**Issue by bert27** [renative-org/renative#671]
I am using android wear api 28 emulator. Hot update doesn't work.

In order to see any changes to the code, you need to compile again. 1 minute and a half approximately.

Do you know of any solution? Thank you.

**Comment by kasinskas** [comment]
https://github.com/pavjacko/renative/blob/363ad04102a385047bf68bcbc0757cd3b3581424/packages/rnv-engine-rn/src/sdks/sdk-android/index.js#L90 

rnv prevents react-native from trying to even connect to the bundler, because of unsupported webview

**Comment by mihaiblaga89** [comment]
considering this closed
