### ISSUE TITLE
How do i open the tizen emulator web inspector?

### ISSUE THREAD

**Issue by guuhgalvao** [renative-org/renative#678]
I need to have access to the console to validate my code, however, I don't know how to open the emulator web inspector in the tizen version

**Comment by Luiz-Monad** [comment]
You can do this. 

```
rnv target launch -p tizen
sdb -s emulator-26101 shell 0 debug YOURAPPID
sdb -s emulator-26101 forward tcp:PORT_FROM_PREVIOUS tcp:PORT_FROM_PREVIOUS
```

I think `rnv debug` should really do this instead of whatever is that it tries to do for Tizen which doesn't work.

**Comment by JoaoCEAlmeida** [comment]
Hi just use my google chrome broswer, with the url and port where the project on tizen is running and test it there.

For example, if the project is running on my localhost port 8087 I just open the http://localhost:8087 on my chrome.

**Comment by mihaiblaga89** [comment]
considering this closed
