### ISSUE TITLE
"rnv run -p androidtv" does not pick up emulator

### ISSUE THREAD

**Issue by Cilveti** [renative-org/renative#679]
**Describe the bug**
When running the command `rnv run -p androidtv`, the build gets built correctly and it says that 
everything has gone ok, but it shows this emulator as the target: `Android_TV_720p_API_22`, which is not my emulator. It looks like the default one. 

It does not seem to recognize that there is an emulator running at all.
I have tried opening the app in Android Studio, where I can actually get it to run on the emulator, but afterwards I need to run the rnv server, and still I only get a black screen for the app.

I have tried setting my emulator name (`Android_TV_1080p_API_26`) as the target but, even though it says that that is the target, it does not launch the app.

**To Reproduce**

1. Run command `rnv run -p androidtv`
2. See error

**Expected behavior**
The app is launched in the emulator

**Screenshots or copy&paste**
![Captura de pantalla 2021-05-20 a las 16 25 15](https://user-images.githubusercontent.com/82807051/118996130-f78f0180-b987-11eb-8ccb-267407059983.png)

**Desktop (please complete the following information):**

-   OS: macOS Catalina 10.15.7
-   Node Version v16.1.0
-   RNV Version 0.31.3

**Additional context**
I have had some trouble installing the necessary SDK tools and such. I ended up using sdkman as well as android studio

**Comment by mihaiblaga89** [comment]
@Cilveti in the latest RNV versions we added better support for default emulators, it will ask you if the default one does not match, to change it. Please give it a shot and reopen the issue if the issue persists
