### ISSUE TITLE
How to embed assets to the web build

### ISSUE THREAD

**Issue by acerbetti** [renative-org/renative#682]
Hi,
I'm starting to investigate this library for some of my projects and it looks very promising.
My setup is MacOS, using version 0.31.3 and the blank template

However, I'm facing an issue when I try to build the code for the web platform. I'm using
`rnv build -p web`

And I can't find the public folder when all the assets should be moved to. 
For example, the favicon.ico never gets copied there.

Am I missing anything?

thanks for the lib and for the help

**Comment by kasinskas** [comment]
Hey, to update assets like favicon you need to put it in appConfigs -> base -> assets -> web. favicon should already be there and if you replace it with the one you want, it will get automatically updated on the next run

**Comment by mihaiblaga89** [comment]
considering this closed
