### ISSUE TITLE
RNV new fails to list platforms on 0.32 alpha version

### ISSUE THREAD

**Issue by CHaNGeTe** [renative-org/renative#689]
**Describe the bug**
Bootstrap a new project with rnv new.
At some step, you are required to opt-in for the platform you want your project to support.
The platform list is empty

**To Reproduce**

1. Run command 'rnv new'
2. Fill in step by step
3. See error when platforms are prompted

**Expected behavior**
Platform list to be shown

**Screenshots or copy&paste**
![image (14)](https://user-images.githubusercontent.com/1237997/122557080-99177a80-d03c-11eb-889f-ad3c5c6421b7.png)

**Desktop (please complete the following information):**

-   OS: osx
-   Node Version v12.16.1
-   RNV Version 0.32.0-alpha.42

**Comment by mihaiblaga89** [comment]
@CHaNGeTe do you still have this issue? IIRC there were some changes in the latest version(0.32.*) that should mitigate this.

**Comment by mihaiblaga89** [comment]
considering this closed
