### ISSUE TITLE
Renative gets stuck while running the command 'npx rnv run -p android' for android

### ISSUE THREAD

**Issue by jasmeet447** [renative-org/renative#691]
**Describe the bug**
My project works fine on ios but as soon as I try to run it for android, the whole process 'Pauses'.  The bug also occours on creating a new Renative Helloworld Templaye also. 
I Don't get any error, it just freezes and I've to restart and same things happen again.

**Expected behavior**
Atleast some logs should be there to help.

**Logs: **

jasmeet-singh:VideoReadyOTT jasmeetsingh$ npx rnv run -p android 

┌──────────────────────────────────────────────────────────────────────────────┐
│                                                                              │
│        ██████╗ ███████╗███╗   ██╗ █████╗ ████████╗██╗██╗   ██╗███████╗       │
│        ██╔══██╗██╔════╝████╗  ██║██╔══██╗╚══██╔══╝██║██║   ██║██╔════╝       │
│        ██████╔╝█████╗  ██╔██╗ ██║███████║   ██║   ██║██║   ██║█████╗         │
│        ██╔══██╗██╔══╝  ██║╚██╗██║██╔══██║   ██║   ██║╚██╗ ██╔╝██╔══╝         │
│        ██║  ██║███████╗██║ ╚████║██║  ██║   ██║   ██║ ╚████╔╝ ███████╗       │
│        ╚═╝  ╚═╝╚══════╝╚═╝  ╚═══╝╚═╝  ╚═╝   ╚═╝   ╚═╝  ╚═══╝  ╚══════╝       │
│                                                                              │
│        Version: 0.30.4                                                       │
│        https://renative.org                                                  │
│        🚀 Firing up!...                                                      │
│        $ rnv run -p android                                                  │
│        Start Time: 20/06/2021, 18:02:42                                      │
│                                                                              │
└──────────────────────────────────────────────────────────────────────────────┘

$ rnv run -p android - cli - Starting!
$ rnv run -p android - _startBuilder:false - Starting!
$ rnv run -p android - checkAndMigrateProject - Starting!
$ rnv run -p android - listAppConfigsFoldersSync:undefined - Starting!
$ rnv run -p android - _migrateProjectSoft - Starting!
$ rnv run -p android - parseRenativeConfigs - Starting!
$ rnv run -p android - matchAppConfigID:undefined
$ rnv run -p android - getWorkspaceDirPath - Starting!
$ rnv run -p android - loadPluginTemplates - Starting!
$ rnv run -p android - _findAndSwitchAppConfigDir:undefined - Starting!
$ rnv run -p android - checkAndMigrateProject - Starting!
$ rnv run -p android - listAppConfigsFoldersSync:undefined - Starting!
$ rnv run -p android - _migrateProjectSoft - Starting!
$ rnv run -p android - parseRenativeConfigs - Starting!
$ rnv run -p android - matchAppConfigID:undefined
$ rnv run -p android - getWorkspaceDirPath - Starting!
$ rnv run -p android - loadPluginTemplates - Starting!
$ rnv run -p android - _findAndSwitchAppConfigDir:undefined - Starting!
$ rnv run -p android - checkAndCreateProjectPackage - Starting!
$ rnv run -p android - configureRnvGlobal - Starting!
$ rnv run -p android - checkIfTemplateInstalled - Starting!
$ rnv run -p android - fixRenativeConfigsSync - Starting!
$ rnv run -p android - checkAndCreateGitignore - Starting!
$ rnv run -p android - configureNodeModules:undefined:undefined - Starting!
$ rnv run -p android - applyTemplate:renative-template-blank=>undefined: - Starting!
$ rnv run -p android - _applyTemplate | current:renative-template-blank | selected:undefined - Starting!
$ rnv run -p android - setAppConfig:blank - Starting!
$ rnv run -p android - _findAndSwitchAppConfigDir:blank - Starting!
$ rnv run -p android - generateLocalConfig:undefined:/Users/jasmeetsingh/VideoReadyRenative/VideoReadyOTT/renative.local.json - Starting!
$ rnv run -p android - getWorkspaceDirPath - Starting!
$ rnv run -p android - generateLocalConfig:false:/Users/jasmeetsingh/VideoReadyRenative/VideoReadyOTT/renative.local.json - Starting!
$ rnv run -p android - configureEntryPoints - Starting!
⚠️  $ rnv run -p android - WARNING: You missing entryFile key for tizenmobile platform in your /Users/jasmeetsingh/VideoReadyRenative/VideoReadyOTT/appConfigs/blank/renative.json.
$ rnv run -p android - configurePlugins - Starting!
⚠️  $ rnv run -p android - WARNING: Plugin react-navigation dependency mismatch (5.2.1) => (3.4.2) .updating npm dependency in your package.json
⚠️  $ rnv run -p android - WARNING: Plugin react-navigation dependency mismatch (5.0.9) => (3.5.0) .updating npm dependency in your package.json
⚠️  $ rnv run -p android - WARNING: Version mismatch of dependency @react-navigation/core between:
/Users/jasmeetsingh/VideoReadyRenative/VideoReadyOTT/package.json: v(3.4.2) and
/Users/jasmeetsingh/VideoReadyRenative/VideoReadyOTT/platformBuilds/blank_android.json: v(5.2.1).
package.json will be overriden
⚠️  $ rnv run -p android - WARNING: Version mismatch of dependency @react-navigation/native between:
/Users/jasmeetsingh/VideoReadyRenative/VideoReadyOTT/package.json: v(3.5.0) and
/Users/jasmeetsingh/VideoReadyRenative/VideoReadyOTT/platformBuilds/blank_android.json: v(5.0.9).
package.json will be overriden
⚠️  $ rnv run -p android - WARNING: Plugin react-native-slider is not recognized plugin in source:rnv scope
⚠️  $ rnv run -p android - WARNING: Plugin with name react-native-slider does not exists in ReNative source:rnv scope. you need to define it manually here: /Users/jasmeetsingh/VideoReadyRenative/VideoReadyOTT/platformBuilds/blank_android.json
$ rnv run -p android - configurePlugins:true
$ rnv run -p android - versionCheck - Starting!
$ rnv run -p android - versionCheck:rnvRunner:0.30.4,rnvProject:0.30.4
$ rnv run -p android - configureNodeModules:true:undefined - Starting!
⚠️  $ rnv run -p android - WARNING: Looks like your node_modules out of date! Let's run npm install first!
$ rnv run -p android - npmInstall - Starting!
$ rnv run -p android - npmInstall: package manager used: (npm install)
⠋ Executing: npm install(node:56514) Warning: Accessing non-existent property 'cat' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
(node:56514) Warning: Accessing non-existent property 'cd' of module exports inside circular dependency
(node:56514) Warning: Accessing non-existent property 'chmod' of module exports inside circular dependency
(node:56514) Warning: Accessing non-existent property 'cp' of module exports inside circular dependency
(node:56514) Warning: Accessing non-existent property 'dirs' of module exports inside circular dependency
(node:56514) Warning: Accessing non-existent property 'pushd' of module exports inside circular dependency
(node:56514) Warning: Accessing non-existent property 'popd' of module exports inside circular dependency
(node:56514) Warning: Accessing non-existent property 'echo' of module exports inside circular dependency
(node:56514) Warning: Accessing non-existent property 'tempdir' of module exports inside circular dependency
(node:56514) Warning: Accessing non-existent property 'pwd' of module exports inside circular dependency
(node:56514) Warning: Accessing non-existent property 'exec' of module exports inside circular dependency
(node:56514) Warning: Accessing non-existent property 'ls' of module exports inside circular dependency
(node:56514) Warning: Accessing non-existent property 'find' of module exports inside circular dependency
(node:56514) Warning: Accessing non-existent property 'grep' of module exports inside circular dependency
(node:56514) Warning: Accessing non-existent property 'head' of module exports inside circular dependency
(node:56514) Warning: Accessing non-existent property 'ln' of module exports inside circular dependency
(node:56514) Warning: Accessing non-existent property 'mkdir' of module exports inside circular dependency
(node:56514) Warning: Accessing non-existent property 'rm' of module exports inside circular dependency
(node:56514) Warning: Accessing non-existent property 'mv' of module exports inside circular dependency
(node:56514) Warning: Accessing non-existent property 'sed' of module exports inside circular dependency
(node:56514) Warning: Accessing non-existent property 'set' of module exports inside circular dependency
(node:56514) Warning: Accessing non-existent property 'sort' of module exports inside circular dependency
(node:56514) Warning: Accessing non-existent property 'tail' of module exports inside circular dependency
(node:56514) Warning: Accessing non-existent property 'test' of module exports inside circular dependency
(node:56514) Warning: Accessing non-existent property 'to' of module exports inside circular dependency
(node:56514) Warning: Accessing non-existent property 'toEnd' of module exports inside circular dependency
(node:56514) Warning: Accessing non-existent property 'touch' of module exports inside circular dependency
(node:56514) Warning: Accessing non-existent property 'uniq' of module exports inside circular dependency
(node:56514) Warning: Accessing non-existent property 'which' of module exports inside circular dependency
✔ Executing: npm install
✔ Executing: npx jetify
$ rnv run -p android - checkCrypto - Starting!
$ rnv run -p android - updateConfig:blank - Starting!
$ rnv run -p android - setAppConfig:blank - Starting!
$ rnv run -p android - _findAndSwitchAppConfigDir:blank - Starting!
$ rnv run -p android - generateLocalConfig:undefined:/Users/jasmeetsingh/VideoReadyRenative/VideoReadyOTT/renative.local.json - Starting!
$ rnv run -p android - getWorkspaceDirPath - Starting!
ℹ️  $ rnv run -p android - NOTE: Current App Config: helloWorld
$ rnv run -p android - _execute:run:null - Starting!
$ rnv run -p android - executePipe:run:before - Starting!
$ rnv run -p android - buildHooks - Starting!
$ rnv run -p android - rnvRun:android - Starting!
$ rnv run -p android - isPlatformSupported:android - Starting!
$ rnv run -p android - checkAndConfigureSdks:android - Starting!
$ rnv run -p android - checkAndConfigureAndroidSdks:android - Starting!
$ rnv run -p android - isBuildSchemeSupported:android - Starting!
$ rnv run -p android - _rnvRunWithPlatform:android - Starting!
$ rnv run -p android - _rnvRunWithPlatform:android:8083:Nexus_5X_API_26:undefined
$ rnv run -p android - checkSdk - Starting!
$ rnv run -p android - _isSdkInstalled: android - Starting!
$ rnv run -p android - configureIfRequired:android - Starting!
$ rnv run -p android - createPlatformBuild:android - Starting!
$ rnv run -p android - cli - Starting!
$ rnv run -p android - _startBuilder:true - Starting!
$ rnv run -p android - _execute:configure:null - Starting!
$ rnv run -p android - executePipe:configure:before - Starting!
$ rnv run -p android - buildHooks - Starting!
$ rnv run -p android - rnvConfigure:android:android - Starting!
$ rnv run -p android - _checkAndCreatePlatforms:android - Starting!
$ rnv run -p android - copyRuntimeAssets - Starting!
$ rnv run -p android - parseFonts - Starting!
$ rnv run -p android - _copySharedPlatform:android - Starting!
$ rnv run -p android - generateRuntimeConfig - Starting!
$ rnv run -p android - overrideTemplatePlugins - Starting!
$ rnv run -p android - parsePlugins:android - Starting!
⚠️  $ rnv run -p android - WARNING: Plugin react-native-slider is not recognized plugin in source:rnv scope
$ rnv run -p android - configureGradleProject:android - Starting!
$ rnv run -p android - copyAssetsFolder:android - Starting!
$ rnv run -p android - configureAndroidProperties:android - Starting!
$ rnv run -p android - configureProject:android - Starting!
$ rnv run -p android - parsePlugins:android - Starting!
⚠️  $ rnv run -p android - WARNING: Plugin react-native-slider is not recognized plugin in source:rnv scope
$ rnv run -p android - parseFonts - Starting!
$ rnv run -p android - parseAppBuildGradleSync - Starting!
$ rnv run -p android - parseAndroidManifestSync:android - Starting!
$ rnv run -p android - parsePlugins:android - Starting!
⚠️  $ rnv run -p android - WARNING: Plugin react-native-slider is not recognized plugin in source:rnv scope
$ rnv run -p android - copyBuildsFolder:android - Starting!
$ rnv run -p android - copyTemplatePluginsSync:android - Starting!
$ rnv run -p android - parsePlugins:android - Starting!
⚠️  $ rnv run -p android - WARNING: Plugin react-native-slider is not recognized plugin in source:rnv scope
$ rnv run -p android - executePipe:configure:after - Starting!
$ rnv run -p android - buildHooks - Starting!
$ rnv run -p android - _startBundlerIfRequired:android - Starting!
$ rnv run -p android - isBundlerActive:android:http://0.0.0.0:8083 - Starting!

**

**Desktop :**

-   OS: MacOS 11.2.3 
-   Node Version: 14.17.1
-   RNV Version: 0.30.4
-   NPM Version: 6.14.13
-   Android Studion Version: 4.2.1

**Comment by mihaiblaga89** [comment]
0.30.4 is quite old. Can you try to update your rnv version and see if that fixes it?

**Comment by mihaiblaga89** [comment]
closing this for now, feel free to reopen if you still encounter the issue
