### ISSUE TITLE
ReNative v 0.32.1 Tizen TV app not loaded

### ISSUE THREAD

**Issue by MomoDeLuxe** [renative-org/renative#738]
**Describe the bug**
App not loaded on TV

**To Reproduce**

1. RNV new project with Hello world
2. Test on TV rnv run -s -p tizen -t TV_IP
3. App white screen

**Expected behavior**
Hello world home page.

**Comment by mihaiblaga89** [comment]
what rnv version are you using?

**Comment by trokohl** [comment]
I have the same issue, it seams that the dev server only listen to 127.0.0.1 and the Apps use the IP


```
Debugger running at: http://192.168.66.74:8079
{ app: undefined }

Dev server running at: http://127.0.0.1:8087
```


http://127.0.0.1:8087 => ansers
http://192.168.66.74:8087 => not

**Comment by trokohl** [comment]
add 
```
"platforms": {
        "tizen": {
            "webpackConfig": {
                "devServerHost": "192.168.66.74"
```
in the renative.json as a workaround

**Comment by MomoDeLuxe** [comment]
setting devServerHost to local machine IP address seems to work

**Comment by saumilshahdct** [comment]
Hi I am facing same issue with renative version 0.37.3. Can someone help?
