### ISSUE TITLE
Multiplatform HLS streaming player examples?

### ISSUE THREAD

**Issue by analyserdmz** [renative-org/renative#744]
Hello, are there any renative multiplatform (aka. Android, MacOS, iOS, Windows, Tizen, WebOS) streaming player examples, as a starting point to understand the logic?

**Comment by ali-sao** [comment]
@analyserdmz , you can create a platform specific base file and use `createElement ` from `react-native-web` like so : 

`import { createElement } from "react-native-web";
const Video = (props) => {
  const attrs = {
    src: props.source,
    poster: props.poster,
    controls: "controls"
  }
  return createElement("video", attrs)
}
export default Video`

Then use it the same way you do with `react-native-video` element :
`<Video
  source={require("./video.mp4")}
  poster={'https://path-to-poster'}
/>`

Furthermore, you can use html5 elements/tags directly inside your codebase, like using <video/> element and it'd be interpretable without further code.

**Comment by mihaiblaga89** [comment]
considering this closed
