### ISSUE TITLE
Existing projects + keeping RN up to date

### ISSUE THREAD

**Issue by sidferreira** [renative-org/renative#752]
I have an existing project using RN 0.66.
Is there any migration guide to use `renative`?
Can I specify rn versions?

**Comment by kasinskas** [comment]
Hey. 0.66 RN is not yet supported by renative, but we're working on it and we're expecting next rnv release to support it. Will let you know when it's done. The migration is pretty simple really, the easiest way is to just create a new project with rnv and copy your src to that new project - https://renative.org/docs/overview/migrating_react_native

**Comment by mihaiblaga89** [comment]
considering this closed
