### ISSUE TITLE
can not bundle project and server into wgt.

### ISSUE THREAD

**Issue by sajjadgrw1** [renative-org/renative#756]
Previously I used Tizen studio and it generate wgt file with all content in it. I recently migrated an app from react-native to renative and am done with the final changes for the TIZEN TV app. I am able to run and debug app on real device. But when i tried to install WGT using sdb, it is not working on tizen because it is not able load server files from my mac machine. 
App is not completely bundled into WGT file. 
I tried other rnv commands like package deploy etc but none of it creates wgt or (tpk not sure)? I am aware of it that we can provide url of our web content in wgt and it works fine even in production. BUT how can i publish RNV app to production? 
I also tried to import tizen output folder to tizen studio but again index.js is having url form local-ip-server which is then targeting to target.js => which is not even present in created project. 
I hope somebody understands the question and responds. Thanks in advance.

**Comment by mihaiblaga89** [comment]
the development app has an "app shell", which is nothing but a simple HTML with a redirect after 5s to your development machine that is running a webpack-dev-server, for easy development and hot reloads. That's why you don't see your app inside the output. You should be able to produce a production build with `rnv export`

**Comment by sajjadgrw1** [comment]
Yes correct this is what i thought first. 
<img width="790" alt="renative" src="https://user-images.githubusercontent.com/4892234/145338963-9cd142f9-cadf-40d6-a449-a9b0cade3094.png">
I have done a workaround, that is copy content from server folder into tizen studio project and created WGT file from tizen studio.

**Comment by pchmelar** [comment]
I was also stuck on this for a while. In the end, I found out that I can produce a release version of `.wgt` by using `rnv build -p tizen -s release`. We should add this into docs.

**Comment by mihaiblaga89** [comment]
updated the docs

**Comment by HatimPatwa** [comment]
Althouh i crea
