### ISSUE TITLE
show error  when npm dist-tag ls renative-template-hello-world

### ISSUE THREAD

**Issue by fanzhiri** [renative-org/renative#757]
npm dist-tag ls renative-template-hello-world 

FAILED with ERROR: 

Command failed with exit code 1 (EPERM): npm dist-tag ls renative-template-hello-world

npm ERR! dist-tag ls Couldn't get dist-tag data for Result {
npm ERR! dist-tag ls   type: 'tag',
npm ERR! dist-tag ls   registry: true,
npm ERR! dist-tag ls   where: undefined,
npm ERR! dist-tag ls   raw: 'renative-template-hello-world',
npm ERR! dist-tag ls   name: 'renative-template-hello-world',
npm ERR! dist-tag ls   escapedName: 'renative-template-hello-world',
npm ERR! dist-tag ls   scope: undefined,
npm ERR! dist-tag ls   rawSpec: '',
npm ERR! dist-tag ls   saveSpec: null,
npm ERR! dist-tag ls   fetchSpec: 'latest',
npm ERR! dist-tag ls   gitRange: undefined,
npm ERR! dist-tag ls   gitCommittish: undefined,
npm ERR! dist-tag ls   hosted: undefined
npm ERR! dist-tag ls }
npm ERR! code E404
npm ERR! 404 Not Found - GET https://repo.huaweicloud.com/repository/npm/-/package/renative-template-hello-world/dist-tags
npm ERR! 404 
npm ERR! 404  'renative-template-hello-world@latest' is not in this registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

**Comment by mihaiblaga89** [comment]
you have a misconfigured `~/.npmrc`. You're pointing all your packages to ` https://repo.huaweicloud.com` registry and the helloworld template is published to npm. You can point only the packages you need from huawei to that repo and leave the rest to npm. 

```
@wateverscopefromhuawei:registry= https://repo.huaweicloud.com/repository/...
```
instead of 
```
registry= https://repo.huaweicloud.com/repository/...
```

**Comment by fanzhiri** [comment]
I change one line in the ~/.npmrc

registry=https://registry.npm.taobao.org/
instead of
registry= https://repo.huaweicloud.com/repository/npm
