### ISSUE TITLE
which video sdk for chromecast

### ISSUE THREAD

**Issue by Leena-Sharma-rsys** [renative-org/renative#772]
which video sdk will be supported to chromecast ?  currenty i am ussing react-native-video as it supports dom, but its not working show blank screen .

**Comment by ali-sao** [comment]
Try another player , react-player would do the job

**Comment by wwwebgainss0** [comment]
Hi @ali-sao I am trying to install this plugin. After running npm install the plugin folder writes to node_modules.
But when I import react player in view and run rnv run -p web . it automatically deletes the plugin folder and I get the error that react-player module is not found and it deletes the folder in node_modules. I would be very happy if you can help me how to install and run this plugin. THX

**Comment by Leena-Sharma-rsys** [comment]
pl

**Comment by Leena-Sharma-rsys** [comment]
hi, @ali-sao  
is there any single player that can be shared over each platform instead of writing platform specific code ?

**Comment by ali-sao** [comment]
@Leena-Sharma-rsys , there is but am afraid nothing is free to use, 

React-native-video was your best option, but if I were you I won’t use it for web based platforms. Rather using it for Native Platforms only.

**Comment by ali-sao** [comment]
@wwwebgainss0 , which version of rnv are you using? 

You’d usually do it via your renative.json file but to my knowledge, it won’t be requires as long as you have it as a dependency in package.json.
