### ISSUE TITLE
Wrong dev host IP

### ISSUE THREAD

**Issue by rokn** [renative-org/renative#773]
**Describe the bug**
When the machine which is hosting the dev server has multiple network adapters the `ip` package is returning wrong IP address, which results in `DEV_SERVER` set to wrong IP address. Maybe using the `devServerHost` from the config(if possible) would fix this issue.

**To Reproduce**

1. Add a network adapter to your machine(for example with a VM or WSL)
2. Try to launch the app with `rnv run`
3. The index.html of the client app contains ` var href = 'http://<IP of the new network adapter>:8087';`

**Expected behavior**
The ip should be the correct IP(wifi or eth) of the host machine.

**Desktop (please complete the following information):**

-   OS: windows 10
-   Node Version v16.13.1
-   RNV Version 0.33.0

**Comment by pavjacko** [comment]
@rokn thanks for reporting this. I think it should be possible to add support for host override in such circumstances. will check it out
