### ISSUE TITLE
Tizen emulator stuck on TV start screen (with colours strip)

### ISSUE THREAD

**Issue by dalalRohit** [renative-org/renative#778]
**Describe the bug**
When I do `rnv run` and choose tizen, it starts the emulator but it gets stuck at that screen only. No movement ahead.

Attaching image for reference: 

![image](https://user-images.githubusercontent.com/32014253/148940083-e49bf1c2-be7e-4b15-b8a8-7beb27eb24dd.png)

**Desktop:**

-   OS: Windows 10
-   Node Version: 16.13.2
-   RNV Version: 0.34.0

**Comment by mihaiblaga89** [comment]
It seems that it doesn't install the app on the simulator. Can you post the full output of the command?

**Comment by dalalRohit** [comment]
steps we did with renative:

- Install tizen studio
- Added Samsung TV Extension from tizen package-manager
- Install renative via cli ```npm i -g rnv```
- Created new renative project by ```rnv new```
-  ```rnv run``` to start the project and emulator
- Emulator starts but only start screen stays, nothing happens ahead. CLI also doesn't show any error, just stays at "Executing.."

Attaching the CLI output as screenshot: 

![image](https://user-images.githubusercontent.com/32014253/149613675-2caca585-5e74-4c61-8ba4-387d53c2236a.png)

Is there anything I'm missing out on? Maybe from tizen-studio?

Thank you,

**Comment by dnsking** [comment]
This bug is related to the Tizen TV emulator and not Renative. It's best for you to test on a real physical device than an emulator

**Comment by mihaiblaga89** [comment]
@dalalRohit can you try to run that command (the one after `Executing`) manually? Maybe it's waiting for some input from you, that's why it's stuck. And since RNV only prints out the last line of the command output you don't see it.

**Comment by mihaiblaga89** [comment]
closing this for now, feel free to reopen if you still encounter the issue
