### ISSUE TITLE
LG WebOS emulator throws "No Java virtual machine was found..." error (see image)

### ISSUE THREAD

**Issue by amodoke** [renative-org/renative#782]
Hi,
So I installed the LG Webos emulator, java runtime, java sdk.

However, when I run the **rnv run -p webos** command, I am getting the following popup:
![java](https://user-images.githubusercontent.com/182899/149618002-eb13934f-516e-43fb-9404-e45d253f1556.png)

What am I doing wrong here?
I have added the paths in the java runtime, also tried changing the path in the windows system environment variables, still the same.

Can someone guide please?

My OS: Windows 10
LG web os emulator is the latest one (6.0.0)

**Comment by ali-sao** [comment]
What usually happens when you try to run a project inside webos IDE? Does
the emulator launches automatically or not?

**Comment by amodoke** [comment]
Weird issues there too...
1. Tried running the renative project through the webos IDE via right-click > run as > webOS application.

It gives the error: "Device not active, please connect the device in target configuration".

Tried doing that in target configuration > throws the error > "Could not connect to the device "emulator", please check the device connection.  

Yes, tried with and without, emulator running and without.
Yes, tried with and without, first running the LG_webOS_TV_Emulator.vbox file.

2. Tried 'installing' the app in the LG virtual tv as well. It does install, but after "launching" it = nothing. Blank screen.

**Comment by dnsking** [comment]
This problem has nothing to do with Renative and is an LG emulator problem, you'll get more help from the LG WebOS developer forum.

**Comment by mihaiblaga89** [comment]
closing this for now
