### ISSUE TITLE
JCenter shutdown 

### ISSUE THREAD

**Issue by luiscerqueira** [renative-org/renative#783]
According to android developer page: 
> JFrog, the company that maintains the JCenter artifact repository used by many Android projects, made JCenter a read-only repository on March 31st, 2021. According to the announcement, JCenter will allow downloads of existing artifacts indefinitely.
Developers who publish artifacts on JCenter should migrate their packages to a new host, such as Maven Central.
Developers who use dependencies from JCenter will need to find the new location of updated versions of those dependencies.

After some research, it's said that JCenter will shut down on Feb 1, 2022. They are recommending developers to migrate from JCenter to mavenCentreal.

This will certainly impact builds for Android based applications, in the worst case scneario, building may not be possible.

My question here is:
- Is renative ready to handle this shutdown?
- Is there any action that we, people who use the renative, have to do? (eg update to latest version, ....)

\cc @pavjacko

**Comment by mihaiblaga89** [comment]
@luiscerqueira we have a fix already for it just not deployed yet. Will be released tomorrow most likely

**Comment by kasinskas** [comment]
@luiscerqueira Please update to the latest rnv (https://github.com/renative-org/renative/releases/tag/0.35.0). The fix was first added in 0.35.0-alpha.4, sorry for not coming back to you to confirm the release earlier
