### ISSUE TITLE
/learn link is broken which is present in README

### ISSUE THREAD

**Issue by DefCon-007** [renative-org/renative#796]
**Describe the bug**
On the readme, in the `Getting Started` section there is a hyperlink to https://renative.org/learn which results in page not found. 

**To Reproduce**
- Open the link https://renative.org/learn

**Expected behavior**
A proper page shoould open 

**Screenshots or copy&paste**
![Screenshot 2022-01-29 at 2 45 41 PM](https://user-images.githubusercontent.com/16754547/151655346-f7c501b1-4f56-47e2-91ad-47997c8ad862.png)
![Screenshot 2022-01-29 at 2 45 45 PM](https://user-images.githubusercontent.com/16754547/151655347-a65ab231-c3ab-4684-9593-73d3c9ec3c42.png)

**Desktop (please complete the following information):**
- N/A

**Additional context**
Since this is the first link on Readme, this should point to proper page.

**Comment by mihaiblaga89** [comment]
fixed by 61e61768f0d59da01825d1d02fa23c7d4d475f75
