### ISSUE TITLE
Tizen video controls

### ISSUE THREAD

**Issue by vladimirgal1012** [renative-org/renative#798]
Hello community,

I searched a web for a few days but cant find any decent solution to my problem. I have a html video in my renative application which plays videos from external URL. The video loads no problem but I can't control it. I have of course enabled the controls for the html video tag but I just can't navigate to them.

Things that I tried with no luck:
- use react-native-video
- use react-player
- add custom controls with listeners but when I go full-screen, I  can't go back

Does anyone know a solution for this please ?

**Comment by mihaiblaga89** [comment]
closing this. Feel free to reopen if you still have problems with it
