### ISSUE TITLE
Can't run renative-template-hello-world on Tizen

### ISSUE THREAD

**Issue by sofiaringstrom** [renative-org/renative#811]
**Describe the bug**
Cannot run the Hello World template on Tizen. Getting `TypeError: Class constructor ServeCommand cannot be invoked without 'new'` on `rnv run`
I can run it without issues on tvOS.

**To Reproduce**
1. Create a new project with `$ rnv` and the `renative-template-hello-world`.
2. `$ rnv run` and select tizen. Complete all the setup (build, asset, chii, etc).
3. Getting `TypeError: Class constructor ServeCommand cannot be invoked without 'new'`.

**Expected behavior**
Be able to run the project in the Tizen emulator.

**Screenshots or copy&paste**
MacBook-McProface:smart-tv sofiaringstrom$ rnv run

┌──────────────────────────────────────────────────────────────────────────────┐
│                                                                              │
│        ██████╗ ███████╗███╗   ██╗ █████╗ ████████╗██╗██╗   ██╗███████╗       │
│        ██╔══██╗██╔════╝████╗  ██║██╔══██╗╚══██╔══╝██║██║   ██║██╔════╝       │
│        ██████╔╝█████╗  ██╔██╗ ██║███████║   ██║   ██║██║   ██║█████╗         │
│        ██╔══██╗██╔══╝  ██║╚██╗██║██╔══██║   ██║   ██║╚██╗ ██╔╝██╔══╝         │
│        ██║  ██║███████╗██║ ╚████║██║  ██║   ██║   ██║ ╚████╔╝ ███████╗       │
│        ╚═╝  ╚═╝╚══════╝╚═╝  ╚═══╝╚═╝  ╚═╝   ╚═╝   ╚═╝  ╚═══╝  ╚══════╝       │
│                                                                              │
│        Version: 0.35.1                                                       │
│        https://renative.org                                                  │
│        🚀 Firing up!...                                                      │
│        $ rnv run                                                             │
│        Start Time: 2/16/2022, 5:19:25 PM                                     │
│                                                                              │
└──────────────────────────────────────────────────────────────────────────────┘

[ task ] registerEngine:engine-core[1]
[ task ] configureRuntimeDefaults[1] appId:null
[ task ] checkAndMigrateProject[1]
[ task ] loadPluginTemplates[1]
[ task ] _parsePluginTemplateDependencies[1] scope:root
[ task ] parseRenativeConfigs[1]
[ task ] getWorkspaceDirPath[1]
[ task ] _generatePlatformTemplatePaths[1]
[ task ] checkAndBootstrapIfRequired[1]
[ task ] loadEngines[1]
[ task ] loadEnginePluginDeps[1]
[ task ] loadEnginePackageDeps[1]
[ task ] findSuitableTask[1]
[ task ] registerAllPlatformEngines[1]
[ task ] registerEngine:engine-rn-web[1]
[ task ] registerEngine:engine-rn-tvos[1]
[ task ] findSuitableTask[2]
? Pick a platform for run tizen
[ info ] Current Engine: engine-rn-web path: ./node_modules/@rnv/engine-rn-web
[ task ] registerMissingPlatformEngines[1]
[ task ] initializeTask[1] run
[ task ] => [run]
[ task ] [run] checkIfProjectAndNodeModulesExists[1]
[ hook ] [run] executePipe ('run:before')
[ task ] [run] taskRnvRun[1] parent:null port:undefined target:undefined hosted:undefined
[ task ] => [run] => [configure]
[ hook ] [configure] executePipe ('configure:before')
[ task ] [configure] taskRnvConfigure[1]
[ task ] => [configure] => [platform configure]
[ hook ] [platform configure] executePipe ('platform:configure:before')
[ task ] [platform configure] taskRnvPlatformConfigure[1] 
[ task ] => [platform configure] => [project configure]
[ hook ] [project configure] executePipe ('project:configure:before')
[ task ] [project configure] taskRnvProjectConfigure[1]
[ task ] [project configure] checkAndMigrateProject[2]
[ task ] [project configure] loadPluginTemplates[2]
[ task ] [project configure] _parsePluginTemplateDependencies[2] scope:root
[ task ] [project configure] parseRenativeConfigs[2]
[ task ] [project configure] getWorkspaceDirPath[2]
[ task ] [project configure] _generatePlatformTemplatePaths[2]
[ task ] => [project configure] => [workspace configure]
[ task ] [workspace configure] taskRnvWorkspaceConfigure[1]
[ task ] <= [project configure] <= workspace configure
[ task ] [project configure] checkIfTemplateConfigured[1]
[ task ] => [project configure] => [install]
[ hook ] [install] executePipe ('install:before')
[ task ] [install] taskRnvInstall[1] requiresInstall:false:true
[ hook ] [install] executePipe ('install:after')
[ task ] <= [project configure] <= install
[ task ] [project configure] checkCrypto[1]
[ task ] [project configure] configureRuntimeDefaults[2] appId:app
[ task ] [project configure] applyTemplate[1] renative-template-hello-world=>undefined
[ task ] [project configure] _applyTemplate[1] current:renative-template-hello-world selected:undefined
[ task ] [project configure] configureRuntimeDefaults[3] appId:app
[ task ] => [project configure] => [install]
[ hook ] [install] executePipe ('install:before')
[ task ] [install] taskRnvInstall[2] requiresInstall:false:true
[ hook ] [install] executePipe ('install:after')
[ task ] <= [project configure] <= install
[ task ] => [project configure] => [app configure]
[ hook ] [app configure] executePipe ('app:configure:before')
[ task ] [app configure] taskRnvAppConfigure[1]
[ task ] [app configure] listAppConfigsFoldersSync[1] ignoreHiddenConfigs:true
[ task ] [app configure] loadPluginTemplates[3]
[ task ] [app configure] _parsePluginTemplateDependencies[3] scope:root
[ task ] [app configure] parseRenativeConfigs[3]
[ task ] [app configure] generateBuildConfig[1] size:139.32 KB
[ task ] [app configure] getWorkspaceDirPath[3]
[ task ] [app configure] generateBuildConfig[2] size:139.32 KB
[ task ] [app configure] generateBuildConfig[3] size:139.32 KB
[ task ] [app configure] generateBuildConfig[4] size:139.32 KB
[ task ] [app configure] _generatePlatformTemplatePaths[3]
[ task ] [app configure] generateBuildConfig[5] size:151.55 KB
[ task ] [app configure] generateBuildConfig[6] size:151.55 KB
[ task ] [app configure] getWorkspaceDirPath[4]
[ task ] [app configure] generateBuildConfig[7] size:151.55 KB
[ task ] [app configure] generateLocalConfig[1] resetAppId:false
[ task ] [app configure] generateBuildConfig[8] size:151.55 KB
[ info ] [app configure] Current App Config: app
[ hook ] [app configure] executePipe ('app:configure:after')
[ task ] <= [project configure] <= app configure
[ task ] [project configure] versionCheck[1]
[ task ] [project configure] versionCheck:rnvRunner:0.35.1,rnvProject:0.35.1[1]
[ task ] [project configure] configureEngines[1]
[ task ] [project configure] resolvePluginDependants[1]
[ task ] [project configure] configurePlugins[1]
[ task ] [project configure] configureRuntimeDefaults[4] appId:app
[ task ] [project configure] copyRuntimeAssets[1]
[ task ] [project configure] configureTemplateFiles[1]
[ task ] [project configure] checkAndCreateGitignore[1]
[ task ] [project configure] checkAndCreateBabelConfig[1]
[ task ] [project configure] generateRuntimeConfig[1]
[ task ] [project configure] overrideTemplatePlugins[1]
[ task ] [project configure] parsePlugins[1]
[ task ] [project configure] parseFonts[1]
[ hook ] [project configure] executePipe ('project:configure:after')
[ task ] <= [platform configure] <= project configure
[ task ] [platform configure] isPlatformSupported[1]
[ task ] [platform configure] checkAndConfigureSdks[1]
[ task ] [platform configure] checkAndConfigureTizenSdks:tizen[1]
[ task ] [platform configure] isBuildSchemeSupported[1]
[ info ] [platform configure] Current Build Scheme: debug
[ task ] [platform configure] checkSdk[1]
[ task ] [platform configure] _isSdkInstalled[1]
[ task ] [platform configure] checkAndConfigureAndroidSdks[1] (/Users/<USER>/Library/Android/sdk)
[ task ] [platform configure] configureRuntimeDefaults[5] appId:app
[ task ] => [platform configure] => [install]
[ hook ] [install] executePipe ('install:before')
[ task ] [install] taskRnvInstall[3] requiresInstall:false:true
[ hook ] [install] executePipe ('install:after')
[ task ] <= [platform configure] <= install
[ task ] [platform configure] [1] taskRnvPlatformConfigure hasBuildFolderPresent:true
[ task ] [platform configure] createPlatformBuild[1]
[ task ] [platform configure] injectPlatformDependencies[1]
[ hook ] [platform configure] executePipe ('platform:configure:after')
[ task ] <= [configure] <= platform configure
[ task ] [configure] configureEntryPoint[1]
[ task ] [configure] copySharedPlatforms[1]
[ task ] [configure] configureTizenProject[1]
[ task ] [configure] configureTizenGlobal[1]
[ task ] [configure] copyAssetsFolder[1]
[ task ] [configure] configureCoreWebProject[1]
[ task ] [configure] _generateWebpackConfigs[1]
[ task ] [configure] parsePlugins[1]
[ task ] [configure] _configureProject[1]
[ task ] [configure] copyBuildsFolder[1]
[ task ] [configure] copyTemplatePluginsSync[1] (./platformBuilds/app_tizen)
[ task ] [configure] parsePlugins[2]
[ hook ] [configure] executePipe ('configure:after')
[ task ] <= [run] <= configure
[ task ] [run] _configureHostedIfRequired[1]
[ task ] [run] runTizen[1] target:undefined
[ task ] [run] runTizen[2] target:undefined hosted:false
[ info ] [run] Your tizen devServer at port 8087 is not running. Starting it up for you...
[ task ] [run] waitForHost[1] port:8087
[ task ] [run] runWeb[1] port:8087 debugger:true
[ info ] [run] Your tizen devServerHost 0.0.0.0 at port 8087 is not running. Starting it up for you...
[ task ] [run] _runWebBrowser[1] ip:0.0.0.0 port:8087 openBrowser:false
┌──────────────────────────────────────────────────────────────────────────────┐
│  🚀  BUNDLER STARTED | 2/16/2022, 5:19:42 PM                                 │
│  $ rnv run                                                                   │
├──────────────────────────────────────────────────────────────────────────────┤
│  ReNative Version: 0.35.1                                                    │
│  Project Name ($package.name): smart-tv                                      │
│  Project Version ($package.version): 0.1.0                                   │
│  Workspace ($.workspaceID): rnv                                              │
│  Platform (-p): tizen                                                        │
│  Engine ($.platforms.tizen.engine): engine-rn-web                            │
│  Template: renative-template-hello-world@0.35.3                              │
│  App Config (-c): app                                                        │
│  Build Scheme (-s): debug                                                    │
│  Target (-t): T-samsung-5.0-x86                                              │
│  Supported Platforms: tizen, tvos, webos                                     │
│  Env Info: darwin | x64 | node v14.17.0                                      │
│  Executed Time: 0h:0m:16s:779ms                                              │
│                                                                              │
│  All good as 🦄                                                              │
│                                                                              │
│  Project location:                                                           │
│  ./platformBuilds/app_tizen/project                                          │
└──────────────────────────────────────────────────────────────────────────────┘
[ task ] [run] _runWebDevServer[1]
[ info ] [run] Starting a remote debugger build with ip 192.168.1.67. If this IP is not correct, you can always override it with --debugIp
2022-02-16 17:19:42 starting server at localhost:8079

Debugger running at: http://192.168.1.67:8079

Dev server running at: http://0.0.0.0:8087

/Users/sofiaringstrom/Documents/Projects/smart-tv/node_modules/webpack-cli/bin/prompt-command.js:108
		require(pathForCmd).default(...args); // eslint-disable-line
		                           ^

TypeError: Class constructor ServeCommand cannot be invoked without 'new'
    at promptForInstallation (/Users/sofiaringstrom/Documents/Projects/smart-tv/node_modules/webpack-cli/bin/prompt-command.js:108:30)
    at /Users/sofiaringstrom/Documents/Projects/smart-tv/node_modules/webpack-cli/bin/cli.js:45:37
    at Object.<anonymous> (/Users/sofiaringstrom/Documents/Projects/smart-tv/node_modules/webpack-cli/bin/cli.js:538:3)
    at Module._compile (internal/modules/cjs/loader.js:1068:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1097:10)
    at Module.load (internal/modules/cjs/loader.js:933:32)
    at Function.Module._load (internal/modules/cjs/loader.js:774:14)
    at Module.require (internal/modules/cjs/loader.js:957:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at runCli (/Users/sofiaringstrom/Documents/Projects/smart-tv/node_modules/webpack-dev-server/bin/webpack-dev-server.js:77:3)
[ hook ] [run] executePipe ('run:after')
[ task ] <= run

 $ rnv run - Done! 🚀
┌──────────────────────────────────────────────────────────────────────────────┐
│  🚀  SUMMARY | 2/16/2022, 5:19:45 PM                                         │
│  $ rnv run                                                                   │
├──────────────────────────────────────────────────────────────────────────────┤
│  ReNative Version: 0.35.1                                                    │
│  Project Name ($package.name): smart-tv                                      │
│  Project Version ($package.version): 0.1.0                                   │
│  Workspace ($.workspaceID): rnv                                              │
│  Platform (-p): tizen                                                        │
│  Engine ($.platforms.tizen.engine): engine-rn-web                            │
│  Template: renative-template-hello-world@0.35.3                              │
│  App Config (-c): app                                                        │
│  Build Scheme (-s): debug                                                    │
│  Target (-t): T-samsung-5.0-x86                                              │
│  Supported Platforms: tizen, tvos, webos                                     │
│  Env Info: darwin | x64 | node v14.17.0                                      │
│  Executed Time: 0h:0m:20s:256ms                                              │
│                                                                              │
│  All good as 🦄                                                              │
│                                                                              │
│  Project location:                                                           │
│  ./platformBuilds/app_tizen/project                                          │
└──────────────────────────────────────────────────────────────────────────────┘

**Desktop (please complete the following information):**

-   macOS Monterey 12.1
-   Node Version 14.17.0
-   RNV Version 0.35.1

**Comment by nakamuraos** [comment]
Seems to be due to a lastest version error of webpack.

This is my quick fix:
```json
    "devDependencies": {
        "@webpack-cli/serve": "^1.6.1",
        "webpack-cli": "^3.3.12",
        "webpack-dev-server": "~3",
    }
```

**Comment by kasinskas** [comment]
0.36.0-canary.1 was released yesterday with webpack sdk updates, please try it out

**Comment by mihaiblaga89** [comment]
closing this for now, feel free to reopen it if the issue persists with the latest update
