### ISSUE TITLE
Where do I put an mp4 asset file?

### ISSUE THREAD

**Issue by crewtaylorfd** [renative-org/renative#812]
Title pretty much says it all. Where do I put an `mp4` asset file and what path do I use if I want to load it? I am trying to play a local file using `react-player` on webOS and Tizen.

**Comment by mihaiblaga89** [comment]
Usually you would not want to embed videos inside apps, you would want to stream it from somewhere, this would be the advice. If you _really_ want to embed it, you can follow the method for adding any other image or asset in general. Place it in `appConfigs/base/assets/runtime`. Those will be copied over into `platformAssets/runtime` at build time, that's how you should reference them in your code. Another option, even worse than the one above, is to put it in `src`
