### ISSUE TITLE
Tizen handle remote button press

### ISSUE THREAD

**Issue by crewtaylorfd** [renative-org/renative#813]
**Describe the bug**
I am working on a Tizen device and I cannot get button presses to register. I have followed instructions [here](https://developer.samsung.com/smarttv/develop/guides/user-interaction/remote-control.html). The basic buttons (directional pad, enter, back) work and I can intercept those keyCode events. However, when I try to register other button presses using the [TizenInputDevice API](https://developer.samsung.com/smarttv/develop/api-references/tizen-web-device-api-references/tvinputdevice-api.html) it does not work. The API is also not initialized. Whenever I try to use the api (e.g. `tizen.tvinputdevice.registerKey('MediaPlay');`) the app freezes. 

**To Reproduce**

1. Put the following code block in a functional component.
```
useEffect(() => {
    const value = tizen.tvinputdevice.getSupportedKeys();
    console.log(value);  
 }, [])
```
2. See error

**Expected behavior**
TizenInputDevice API is called and `value` is logged 

**Desktop (please complete the following information):**

-   OS: osx, running on SamsungTV physical device
-   Node Version 17.0.1
-   RNV Version 0.34.0

**Comment by sande265** [comment]
You Need to build the app rather than run the app in debug mode to get the value, i know it is what it is.

**Comment by mihaiblaga89** [comment]
@crewtaylorfd Samsung for some reason does not expose the API in debug mode.
