### ISSUE TITLE
Using custom fonts in tizen doesn't work

### ISSUE THREAD

**Issue by jolisophilabs** [renative-org/renative#815]
**Describe the bug**
Hello
I am trying to use custom fonts in a tizen project, with renative and react-native. Following the doc, I added the fonts to the appConfigs/base/fonts folder, but when I try to use them they won't load into the components.

I also follow this issue, but it's the same : 

https://github.com/renative-org/renative/issues/405

```
   "react-native": "0.63.4",
    "renative": "0.32.0-feat-asdk-6",
```

**Desktop**

-   OS: MacOS Big Sur
-   Node Version v14.17.0
-   RNV Version 0.32.0-feat-asdk-6

**Comment by sande265** [comment]
try Cleaning the app cache & use different version of renative.
i had issues using icons from rentive Icon, but after changing renative version it worked & i have not faced such issue since & i can import custom icons ass well

**Comment by NickAVolpe** [comment]
> 

@sande265  What version did you switch to?

**Comment by sande265** [comment]
0.34.0

**Comment by mihaiblaga89** [comment]
@jolisophilabs @NickAVolpe please update to the latest version and see if it works. Gonna close this issue for now, if you encounter this with the latest version feel free to open it again
