### ISSUE TITLE
Unable to use installed package in android & androidTV.

### ISSUE THREAD

**Issue by sande265** [renative-org/renative#816]
Due to renative disabling auto link of packages while auto install, i am not able to find how should i use newly install packages as its not binding nor can i manually bind due to react-native being version > V60.

Can anyone help me regarding this issue.

[Mon Feb 21 2022 10:58:20.172]  ERROR    Error: [@RNC/AsyncStorage]: NativeModule: AsyncStorage is null.

To fix this issue try these steps:

  • Rebuild and restart the app.

  • Run the packager with `--reset-cache` flag.

  • If you are using CocoaPods on iOS, run `pod install` in the `ios` directory and then rebuild and re-run the app.

  • If this happens while testing with Jest, check out docs how to integrate AsyncStorage with it: https://react-native-async-storage.github.io/async-storage/docs/advanced/jest

If none of these fix the issue, please open an issue on the Github repository: https://github.com/react-native-async-storage/async-storage/issues

[Mon Feb 21 2022 10:58:20.174]  ERROR    Invariant Violation: Module AppRegistry is not a registered callable module (calling runApplication)
[Mon Feb 21 2022 10:58:20.174]  ERROR    Invariant Violation: Module AppRegistry is not a registered callable module (calling runApplication)

**Comment by mihaiblaga89** [comment]
we have `@react-native-community/async-storage` supported, you can just add it with `rnv plugin add`, or manually adding it in `renative.json` under plugins, following the rest of them. However, if you want to support `react-native-async-storage` you'll have to add it in `renative.json` as an object, following [this file](https://github.com/renative-org/renative/blob/canary/packages/rnv/pluginTemplates/renative.plugins.json) as example. Feel free to reach out if you encounter any more issues
