### ISSUE TITLE
BrowseFragment alternate or a way to use in AndroidTV?

### ISSUE THREAD

**Issue by Shashank2406** [renative-org/renative#818]
Is there an alternate in Renative for BrowseFragment? Or Is there a way to implement BrowseFragment in Renative?

**Comment by aurimasmi** [comment]
Renative doesn't gave BrowseFragment and afair there is no RN plugin out there which does have this implementation. You can check this library https://github.com/reactseals/react-native-leanback which has some leanback features implemented and using this concept you might be able to implement BrowseFragment

**Comment by mihaiblaga89** [comment]
Closing this. If you have any more questions feel free to reopen it or open a new one.
