### ISSUE TITLE
How to launch Tizen Simulator on Renative ? Stuck with an error

### ISSUE THREAD

**Issue by Kunwar01899** [renative-org/renative#829]
I am trying to launch Tizen Simulator on Renative using the command "rnv target launch -p tizen -t T-samsung-6.0-x86" in cmd.
But it keeps giving me this error "Location of your cli undefined does not exists. check your C:\Users\DELL\.rnv\renative.json file if your sdks paths are correct", I'm stuck here, can anyone pls help me out ?

**Comment by Kunwar01899** [comment]
Can you please explain what fixes you have done for the issue I mentioned ?

**Comment by mihaiblaga89** [comment]
it should now configure the correct paths for the sdk so you won't get an error that it's not set up when it actually is. Please give the latest version a go and feel free to reopen this issue if the problem persists

**Comment by Kunwar01899** [comment]
Hi, I'm using Windows 10 OS, when I'm trying to run ReNative Hello World Template on Tizen Simulator , it keeps giving me same error "[ error ] [target launch] Location of your cli undefined does not exists. check your C:\Users\DELL\.rnv\renative.json file if your sdks paths are correct", please help me out with this.
