### ISSUE TITLE
[iOS, tvOS, ATV, Android, macOS, fireTV] [Regression] Template starter app crashes when "Now Try Me!" is clicked

### ISSUE THREAD

**Issue by pauliusguzas** [renative-org/renative#881]
**Describe the bug**
Template starter app crashes when "Now Try Me!" is clicked

**To Reproduce**
1. Run template starter app
2. Click "Now Try Me!" -> crash

**Expected behavior**
My Page should open

**Screenshots or copy&paste**
![Screenshot 2022-06-20 at 10 25 52](https://user-images.githubusercontent.com/65670660/174575337-5d7270c8-aee5-42ca-86e7-b048dd9509b3.png)

**Desktop (please complete the following information):**
- OS: macOS Monterey 12.4
- Node Version: 16.14.0
- RNV Version: 0.36.1-canary.2
- @rnv/template-starter: 0.36.1-canary.2

**Comment by GabrieleKaceviciute** [comment]
It works on v 0.36.2-canary.3 (not tested on fireTV).

**Comment by pauliusguzas** [comment]
Fixed
