### ISSUE TITLE
Error: The package doesn't seem to be linked.

### ISSUE THREAD

**Issue by jonathankiefer** [renative-org/renative#898]
I'm trying to integrate THEOplayer into the starter template, but there appears to be an issue with it not getting linked.

Steps to reproduce:

1. Create reNative project with "rnv new" and all prompt defaults
2. Initialize Android platform with "rnv run -p android"
3. Install THEOplayer: "npm i react-native-theoplayer"
4. Modify ./src/screens/Home.tsx to load THEOplayerView Component
6. Re-run android platform with "rnv run -p android"

Error: The package 'react-native-theoplayer' doesn't seem to be linked.

I tried running "npx react-native link", but that did not help.
I have verified that react-native-theoplayer was successfully installed and included in package.json.

![theo_error](https://user-images.githubusercontent.com/10038122/181845294-17429672-8f86-4561-a2ef-0f25f410af0a.png)

**Comment by tvanlaerhoven** [comment]
@jonathankiefer It looks like autolinking is disabled, as mentioned in the settings.gradle:

```
// ReNative: To allow dynamic plugins via flavours autolinking has to be disabled
// apply from: file("../../node_modules/@react-native-community/cli-platform-android/native_modules.gradle"); applyNativeModulesSettingsGradle(settings, '../..')
// include ':app'
```

You can add react-native-theoplayer as a plugin in your renative.json configuration after installing it via yarn or npm:

```
    "plugins": {
        // ...
        "react-native-theoplayer": {
            "version": "1.3.0",
            "android": {
                "package": "com.theoplayer.ReactTHEOplayerPackage",
                "path": "node_modules/react-native-theoplayer/android",
                "app/build.gradle": {
                    "apply": [
                        "from: '../../../local.gradle'"
                    ]
                }
            }
        }
    }
```

I still had an issue with duplicate 'META-INF/kotlin-stdlib.kotlin_module' files, which I resolved by creating the local `local.gradle` file in your project root:

```
android {
    packagingOptions {
      exclude 'META-INF/kotlin-stdlib.kotlin_module'
    }
}
```

As the build.gradle files under platformBuilds are generated, we cannot simply add the extra gradle options there, hence the reference to the extra local.gradle file.

**Comment by jonathankiefer** [comment]
@tvanlaerhoven I can confirm this is exactly the information I needed, thank you.

**Comment by andread95** [comment]
Hi there,

I'm experiencing the same issue using: 
- Renative 0.37.3
- react-native-theoplayer@2.9.0

I've already tried adding this kind of configuration in renative.json in "plugins", but still returning
```
"react-native-theoplayer": {
            "version": 2.9.0",
            "android": {
                "package": "com.theoplayer.ReactTHEOplayerPackage",
                "path": "node_modules/react-native-theoplayer/android"
            }
        }
```

Any clue? Thank you

<img width="1326" alt="Screenshot 2023-12-05 alle 02 03 10" src="https://github.com/flexn-io/renative/assets/8678965/eb118ba5-b21f-43e5-b246-2c035d185b9a">
