### ISSUE TITLE
All Network Requests Fail in Android TV Build

### ISSUE THREAD

**Issue by jonathankiefer** [renative-org/renative#900]
All network requests are failing when an app is ran in the Android TV emulator. These same requests work fine in the Android emulator.

I have verified that  `./platformBuilds/app_androidtv/app/src/main/AndroidManifest.xml` contains `<uses-permission android:name="android.permission.INTERNET" />`.

Steps to reproduce:
1. `rnv new` with default prompts.
2. Modify Home.tsx screen to execute a network request, e.g.
```
useEffect(() => {
  fetch('https://api.publicapis.org/entries')
     .then((response) => response.json())
     .then((data) => console.log(data));
}, []);
```
3. Run Android TV build: `rnv run -p androidtv`

Fetch request fails with "TypeError: Network request failed".

**Comment by EyMaddis** [comment]
Did you try a cold boot of the emulator? I had this before when I was starting a Web Development Proxy called Charles. 
I recreated the emulator and everything was fine again.

**Comment by jonathankiefer** [comment]
Yeah, I've tried restarting the emulator, and I'm definitely not running a software proxy.

**Comment by jonathankiefer** [comment]
Not sure what the issues was, but reinstalling Android studio and virtual devices fixed it.
