### ISSUE TITLE
[tvOS] Focus issue on Apple TV

### ISSUE THREAD

**Issue by SandeepKharbanda** [renative-org/renative#902]
Hi,

We are developing a project in Renative. The application works fine on iOS, Android, and Android TV platforms. But we observed the focus issue when we try to run the project on Apple TV. The focus is working fine on Android TV.  

So, could you please help us to identify the problem?

Any suggestion/comments will be appreciated.

**Comment by ali-sao** [comment]
صنديب خربندا

**Comment by himanshuttn** [comment]
Facing the same issue.

**Comment by mihaiblaga89** [comment]
please check #917
