### ISSUE TITLE
[Android, AndroidTV] Can't run Android apps on M1 mac

### ISSUE THREAD

**Issue by pauliusguzas** [renative-org/renative#907]
**Describe the bug**
Can't run Android apps on M1 mac

**To Reproduce**
1. Create new project with `rnv new`
2. Do `rnv run -p android` or  `rnv run -p androidtv` -> error

**Expected behavior**
Chosen template should run

**Screenshots or copy&paste**
![image](https://user-images.githubusercontent.com/65670660/186843474-0b4d0ad4-92f6-4ed9-8ea7-7d379915a6c5.png)

**Desktop (please complete the following information):**

-   OS: Monterey 12.3.1
-   Node Version 16.14.2
-   RNV Version 0.36.2-canary.4
-   Android Studio 2021.2.1 Patch 2

**Additional context**
Template used @rnv/template-starter@0.36.2-canary.4

**Comment by pauliusguzas** [comment]
Cross checked on other M1 mac with 16.14.2 node and 11.6 os version and it works

**Comment by mihaiblaga89** [comment]
@pauliusguzas it seems like your configured NDK folder is not correct. Looking at the error it says that the NDK folder does not contain `source.properties`

**Comment by pauliusguzas** [comment]
Resolved by adding full path to ndk including directory with version number of ndk
