### ISSUE TITLE
[tvOS] Focus not working on tvOS

### ISSUE THREAD

**Issue by himanshuttn** [renative-org/renative#917]
**Describe the bug**
I created a new Renative app using command **rnv new**. I've chosen the template **renative-template-hello-world**. My rnv version is 0.34. When I'm running the sample application on tvOS, its focus is not working. For focus, do i need to setup something additional?

Please help me with this.

**Comment by mihaiblaga89** [comment]
@himanshuttn please update to latest `rnv`, 34 is quite old. In this latest version the template has also been renamed to `@rnv/template-starter`

![CleanShot 2022-09-22 at 10 11 47](https://user-images.githubusercontent.com/4787898/191681967-f2ed7fa3-da4e-48a7-8fd8-9226983ca41c.gif)
