### ISSUE TITLE
Android tv starter template not working

### ISSUE THREAD

**Issue by jnaxo** [renative-org/renative#960]
**Describe the bug**
Command `rnv run -p androidtv` throw a building error in version 0.36.1 for android tv emulator. 

**To Reproduce**

1. Run command `rnv run -p androidtv`
2. See error:
```
Execution failed for task ':react-native-community-masked-view:generateDebugRFile'.
> Could not resolve all files for configuration ':react-native-community-masked-view:debugCompileClasspath'.
   > Failed to transform react-native-0.71.0-rc.0-debug.aar (com.facebook.react:react-native:0.71.0-rc.0) to match attributes {artifactType=android-symbol-with-package-name, com.android.build.api.attributes.BuildTypeAttr=debug, org.gradle.category=library, org.gradle.dependency.bundling=external, org.gradle.libraryelements=aar, org.gradle.status=release, org.gradle.usage=java-api}.
      > Execution failed for JetifyTransform: /Users/zeek/.gradle/caches/modules-2/files-2.1/com.facebook.react/react-native/0.71.0-rc.0/7a7f5a0af6ebd8eb94f7e5f7495e9d9684b4f543/react-native-0.71.0-rc.0-debug.aar.
         > Java heap space
```

**Expected behavior**
Run starter template in android tv emulator

**Screenshots or copy&paste**
If applicable, copy&paste the output of the command. **Run the command with `-i` to get more debugging informations**

**Desktop (please complete the following information):**

-   OS: [osx m1 pro]
-   Node Version [16.15.1]
-   RNV Version [e.g. 0.36.1]

**Additional context**

Platform (-p): androidtv                                                    
Engine ($.platforms.androidtv.engine): engine-rn-tvos                       
Template: @rnv/template-starter@0.36.1                                      
App Config (-c): app                                                        
Build Scheme (-s): debug                                                    
Target (-t): Android_TV_720p_API_22                                         
Supported Platforms: androidtv                                              
Env Info: darwin | arm64 | node v16.15.1

**Comment by wilson208** [comment]
@jnaxo have you found a solution to this? I have spun up a clean projects with versions 0.36.1 and 0.35.4 and running into this issue. I can solve it by manually editing the platformBuilds for each platform and running ./gradlew manually, but rnv overwrites these changes on next run.

**Comment by jnaxo** [comment]
Hi, finally got to a solution updating to `0.37.0-canary-4` but I have to modify a lot of configurations and fix some android implementations in build gradle.
