### ISSUE TITLE
Error while creating a new project

### ISSUE THREAD

**Issue by lizozom** [renative-org/renative#965]
**Describe the bug**
I'm trying to create a new project and I'm receiving the following error:

`[ error ] [new] yarn add @rnv/template-starter@0.36.1 : FAILED. this could happen if you have package.json accidentally created somewhere in parent directory
`
https://github.com/renative-org/renative/blob/cafec1e59a558ed91cb8860fc00889a3d481e0cb/packages/rnv/src/engine-core/tasks/task.rnv.new.js#L378

I checked and there is no `package.json` in any of the parent directories.

**To Reproduce**

1. Run `rnv new`
2. Follow all installation steps
3. Error is shown

**Expected behavior**
Project should be created

**Screenshots or copy&paste**
![image](https://user-images.githubusercontent.com/3016806/221680380-ddd65d2e-f8d5-40ee-a496-8859bbc2c12e.png)

If applicable, copy&paste the output of the command. **Run the command with `-i` to get more debugging informations**

**Desktop (please complete the following information):**

-   OS: Ubuntu 22.04
-   Node Version v16.18.1
-   RNV Version 0.36.1

**Additional context**

**Comment by lizozom** [comment]
Seems like this is a duplicate of https://github.com/renative-org/renative/issues/922

But it also seems like somewhere in the process of installing rnx, I had a bunch of files dumped into my root folder

![image](https://user-images.githubusercontent.com/3016806/221786284-8d2562de-b9f5-45b0-8985-0f8940791113.png)

**Comment by pauliusguzas** [comment]
@lizozom thanks for reporting an issue, I have experienced similar issue. I would suggest checking that there is no `package.json` in root directory and also install rnv globally (prefer using yarn)

**Comment by pauliusguzas** [comment]
Closing as this is most probable cause, feel free to reopen again

**Comment by thornbill** [comment]
I am encountering what seems to be the same issue. The new task is _creating_ a package.json (and lockfile) in my home directory and then errors out.

```sh
➔ cat ~/package.json
{
  "dependencies": {
    "@rnv/template-starter": "^0.36.1"
  }
}
```
