### ISSUE TITLE
Where to add android manifest user-permitions

### ISSUE THREAD

**Issue by saimirg** [renative-org/renative#981]
Hi,
i'm trying to add the following permission on androidtv `<uses-permission android:name="android.permission.ACCESS_NETWORK_STATE"/>` by adding it in almost any _renative.json_ file but without success. I can see permission added on the merged final json file _platformBuilds/app_androidtv.json_ but not on the Android Manifest file.

**Comment by pauliusguzas** [comment]
@saimirg Thanks for this question, could you provide rnv and node versions, os type?

**Comment by saimirg** [comment]
Hi @pauliusguzas, after several test i was able to make it work by adding the following section:

`   "permissions": {
        "ios": {},
        "android": {
            "INTERNET": {
                "key": "android.permission.INTERNET",
                "security": "normal"
            },
            "ACCESS_NETWORK_STATE": {
                "key": "android.permission.ACCESS_NETWORK_STATE",
                "security": "normal"
            }
        }
    }`
